#!/bin/bash

# SSH Key Generation Demo Script
# This script demonstrates how to use the new SSH key generation feature in Terraform

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║     Azure ALZ - SSH Key Generation Feature Demo                           ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Function to display colored output
info() {
    echo "ℹ️  $1"
}

success() {
    echo "✅ $1"
}

warning() {
    echo "⚠️  $1"
}

error() {
    echo "❌ $1"
}

# Demo mode check
if [ "$1" == "--demo" ]; then
    DEMO_MODE=true
    info "Running in DEMO MODE - no actual Terraform changes will be made"
else
    DEMO_MODE=false
fi

echo ""
echo "═════════════════════════════════════════════════════════════════════════════"
echo "SCENARIO 1: Using Local SSH Key (Production Recommended)"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""

info "This approach uses an existing SSH key file for better security."
echo ""
echo "Configuration:"
echo "  generate_ssh_key = false"
echo "  ssh_public_key_path = \"~/.ssh/id_rsa.pub\""
echo ""

info "Prerequisites:"
echo "  1. Generate SSH key (if not already done):"
echo "     $ ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa"
echo ""
echo "  2. Ensure terraform.tfvars has:"
echo "     generate_ssh_key = false"
echo "     ssh_public_key_path = \"~/.ssh/id_rsa.pub\""
echo ""

if [ "$DEMO_MODE" = false ]; then
    info "Running: terraform validate"
    terraform validate >/dev/null 2>&1 && success "Configuration is valid" || error "Configuration validation failed"
fi

echo ""

echo "═════════════════════════════════════════════════════════════════════════════"
echo "SCENARIO 2: Let Terraform Generate SSH Key (Development Only)"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""

warning "This approach stores the private key in Terraform state file."
warning "Use this ONLY for development/testing environments!"
echo ""
echo "Configuration:"
echo "  generate_ssh_key = true"
echo ""

info "Setup steps:"
echo "  1. Update terraform.tfvars:"
echo "     generate_ssh_key = true"
echo ""
echo "  2. Run terraform apply:"
echo "     $ terraform apply"
echo ""
echo "  3. Extract the private key:"
echo "     $ terraform output -raw ssh_private_key_pem > ~/.ssh/tf_vm_key"
echo "     $ chmod 600 ~/.ssh/tf_vm_key"
echo ""
echo "  4. Connect to VM:"
echo "     $ ssh -i ~/.ssh/tf_vm_key azureuser@<vm_public_ip>"
echo ""

echo ""
echo "═════════════════════════════════════════════════════════════════════════════"
echo "USEFUL COMMANDS"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""

info "Check if SSH key generation is enabled:"
echo "  $ terraform output ssh_key_generated"
echo ""

info "View SSH key configuration:"
echo "  $ terraform output ssh_key_info"
echo ""

info "Get public key (when generated by Terraform):"
echo "  $ terraform output ssh_public_key_openssh"
echo ""

info "Get private key (when generated by Terraform):"
echo "  $ terraform output -raw ssh_private_key_pem > key.pem"
echo "  $ chmod 600 key.pem"
echo ""

info "View VM connection information:"
echo "  $ terraform output connection_info"
echo ""

info "View all compute module outputs:"
echo "  $ terraform output -json | jq '.[] | select(.value | type == \"object\") | select(.value.ssh_key_generated != null)'"
echo ""

echo ""
echo "═════════════════════════════════════════════════════════════════════════════"
echo "SECURITY RECOMMENDATIONS"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""

echo "✓ For Production Environments:"
echo "  - Use LOCAL SSH KEY approach (generate_ssh_key = false)"
echo "  - Manage SSH keys outside of Terraform"
echo "  - Protect Terraform state file with remote backend"
echo "  - Implement strict access controls to state files"
echo ""

echo "✓ For Development Environments:"
echo "  - Use Terraform-generated keys only for temporary resources"
echo "  - Store generated private keys securely (not in Git)"
echo "  - Consider using local_file provider to auto-save keys"
echo "  - Regularly rotate keys"
echo ""

echo "✓ State File Protection (both scenarios):"
echo "  - Use remote backend (Azure Blob Storage, Terraform Cloud, etc.)"
echo "  - Enable encryption at rest"
echo "  - Limit access via IAM/RBAC"
echo "  - Audit state file access"
echo ""

echo ""
echo "═════════════════════════════════════════════════════════════════════════════"
echo "CURRENT CONFIGURATION STATUS"
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""

if [ -f terraform.tfvars ]; then
    GENERATE_SSH_KEY=$(grep "generate_ssh_key" terraform.tfvars | grep -v "^#" | awk '{print $NF}' | tr -d '\r')
    SSH_KEY_PATH=$(grep "ssh_public_key_path" terraform.tfvars | grep -v "^#" | awk -F'"' '{print $2}' | tr -d '\r')
    
    echo "Current Settings:"
    echo "  generate_ssh_key = $GENERATE_SSH_KEY"
    echo "  ssh_public_key_path = \"$SSH_KEY_PATH\""
    echo ""
    
    case "$GENERATE_SSH_KEY" in
        true)
            warning "Terraform will GENERATE a new SSH key pair"
            warning "Private key will be stored in Terraform state file"
            info "This is suitable for DEV/TEST environments only"
            ;;
        false)
            success "Using LOCAL SSH KEY file"
            info "Private key remains on your local system"
            if [ -f "$HOME/.ssh/id_rsa.pub" ] && [ "$SSH_KEY_PATH" == "~/.ssh/id_rsa.pub" ]; then
                success "Local SSH key found at $SSH_KEY_PATH"
            else
                warning "SSH key not found at $SSH_KEY_PATH"
                info "Generate it with: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa"
            fi
            ;;
        *)
            error "Unknown value for generate_ssh_key: $GENERATE_SSH_KEY"
            ;;
    esac
else
    warning "terraform.tfvars not found"
    info "Copy from terraform.tfvars (or create if needed)"
fi

echo ""
echo "═════════════════════════════════════════════════════════════════════════════"
echo "Next Steps:"
echo ""
echo "1. Choose your SSH key approach:"
echo "   - Production: Use local SSH key (generate_ssh_key = false)"
echo "   - Development: Generate via Terraform (generate_ssh_key = true)"
echo ""
echo "2. Configure terraform.tfvars accordingly"
echo ""
echo "3. Run: terraform plan"
echo "   to review the planned changes"
echo ""
echo "4. Run: terraform apply"
echo "   to deploy the resources"
echo ""
echo "5. For generated keys, extract the private key:"
echo "   terraform output -raw ssh_private_key_pem > key.pem && chmod 600 key.pem"
echo ""
echo "═════════════════════════════════════════════════════════════════════════════"
echo ""

success "Demo complete! Review the steps above and proceed with your deployment."
