# modules/compute/outputs.tf - Compute Module Outputs

output "resource_group_name" {
  description = "Name of the compute resource group"
  value       = var.deploy_compute_resources ? azurerm_resource_group.compute[0].name : null
}

output "resource_group_id" {
  description = "ID of the compute resource group"
  value       = var.deploy_compute_resources ? azurerm_resource_group.compute[0].id : null
}

output "vm_id" {
  description = "ID of the virtual machine"
  value       = var.vm_os_type == "linux" ? (var.deploy_compute_resources ? azurerm_linux_virtual_machine.vm[0].id : null) : (var.deploy_compute_resources ? azurerm_windows_virtual_machine.vm_windows[0].id : null)
}

output "vm_name" {
  description = "Name of the virtual machine"
  value       = var.vm_os_type == "linux" ? (var.deploy_compute_resources ? azurerm_linux_virtual_machine.vm[0].name : null) : (var.deploy_compute_resources ? azurerm_windows_virtual_machine.vm_windows[0].name : null)
}

output "vm_private_ip" {
  description = "Private IP address of the VM"
  value       = var.deploy_compute_resources ? azurerm_network_interface.vm_nic[0].private_ip_address : null
}

output "vm_public_ip" {
  description = "Public IP address of the VM (if assigned)"
  value       = var.assign_public_ip && var.deploy_compute_resources ? azurerm_public_ip.vm_public_ip[0].ip_address : null
}

output "vm_public_ip_id" {
  description = "ID of the public IP address"
  value       = var.assign_public_ip && var.deploy_compute_resources ? azurerm_public_ip.vm_public_ip[0].id : null
}

output "network_security_group_id" {
  description = "ID of the network security group"
  value       = var.deploy_compute_resources ? azurerm_network_security_group.vm_nsg[0].id : null
}

output "network_security_group_name" {
  description = "Name of the network security group"
  value       = var.deploy_compute_resources ? azurerm_network_security_group.vm_nsg[0].name : null
}

output "network_interface_id" {
  description = "ID of the network interface"
  value       = var.deploy_compute_resources ? azurerm_network_interface.vm_nic[0].id : null
}

output "connection_info" {
  description = "Connection information for the VM"
  value = var.deploy_compute_resources ? {
    os_type     = var.vm_os_type
    private_ip  = azurerm_network_interface.vm_nic[0].private_ip_address
    public_ip   = var.assign_public_ip ? azurerm_public_ip.vm_public_ip[0].ip_address : "N/A"
    username    = var.admin_username
    ssh_command = var.vm_os_type == "linux" && var.assign_public_ip ? "ssh -i <your_private_key> ${var.admin_username}@${azurerm_public_ip.vm_public_ip[0].ip_address}" : "N/A"
  } : null
}

output "monitor_identity_id" {
  description = "ID of the managed identity used for Azure Monitor Agent"
  value       = var.enable_azure_monitor && var.deploy_compute_resources ? azurerm_user_assigned_identity.vm_monitor_identity[0].id : null
}

output "monitor_identity_principal_id" {
  description = "Principal ID of the managed identity for role assignments"
  value       = var.enable_azure_monitor && var.deploy_compute_resources ? azurerm_user_assigned_identity.vm_monitor_identity[0].principal_id : null
}

output "diagnostic_setting_id" {
  description = "ID of the diagnostic setting for VM metrics (configured in root module)"
  value       = var.enable_azure_monitor && var.deploy_compute_resources ? "Configured via root module" : null
}

output "monitoring_info" {
  description = "Azure Monitor configuration summary"
  value = var.enable_azure_monitor && var.deploy_compute_resources ? {
    monitor_enabled            = true
    agent_type                 = var.vm_os_type == "linux" ? "AzureMonitorLinuxAgent" : "AzureMonitorWindowsAgent"
    managed_identity_id        = azurerm_user_assigned_identity.vm_monitor_identity[0].id
    log_analytics_enabled      = var.log_analytics_workspace_id != "" ? true : false
    log_analytics_workspace_id = var.log_analytics_workspace_id != "" ? var.log_analytics_workspace_id : "N/A"
    metrics_collection_enabled = var.log_analytics_workspace_id != "" ? true : false
  } : null
}

output "ssh_key_generated" {
  description = "Whether SSH key was generated by Terraform"
  value       = var.generate_ssh_key ? true : false
}

output "ssh_private_key_pem" {
  description = "Private SSH key in PEM format (when generated by Terraform). WARNING: This key is stored in Terraform state file!"
  value       = var.generate_ssh_key && var.deploy_compute_resources ? tls_private_key.vm_key[0].private_key_pem : null
  sensitive   = true
}

output "ssh_public_key_openssh" {
  description = "Public SSH key in OpenSSH format (when generated by Terraform)"
  value       = var.generate_ssh_key && var.deploy_compute_resources ? tls_private_key.vm_key[0].public_key_openssh : null
}

output "ssh_key_info" {
  description = "SSH key configuration summary"
  value = var.deploy_compute_resources ? {
    key_generation_enabled = var.generate_ssh_key
    key_source             = var.generate_ssh_key ? "Terraform (tls_private_key)" : "Local file (${var.ssh_public_key_path})"
    warning                = var.generate_ssh_key ? "Private key is stored in Terraform state file. Secure the state file and consider using terraform state commands to view/rotate keys." : null
  } : null
}
